[package]
name = "progetto-pds-backup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circular-buffer = "0.1.7"
enigo = "0.2.1"
euclid = "0.22.10"
rodio = "0.19.0"
